services:
  todo_app:
    build: .
    networks:
      - app-tier
    volumes:
      - .:/app
    env_file:
      - .docker_env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.13-alpine3.20
    ports:
    - "5432:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydata"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-tier:
    driver: bridge

volumes:
  pg_data: